// <auto-generated />
using Asynkron.OtelReceiver.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Asynkron.OtelReceiver.Migrations
{
    [DbContext(typeof(OtelReceiverContext))]
    [Migration("20250929172403_LogAttributeIndexing")]
    partial class LogAttributeIndexing
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Asynkron.OtelReceiver.Data.LogAttributeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LogId")
                        .HasColumnType("integer");

                    b.Property<byte>("Source")
                        .HasColumnType("smallint");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Key");

                    b.HasIndex("LogId");

                    b.HasIndex("Value");

                    b.HasIndex("Key", "Value");

                    b.ToTable("LogAttributes");
                });

            modelBuilder.Entity("Asynkron.OtelReceiver.Data.LogEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("ObservedTimestamp")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("Proto")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("RawBody")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte>("SeverityNumber")
                        .HasColumnType("smallint");

                    b.Property<string>("SeverityText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SpanId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Timestamp")
                        .HasColumnType("bigint");

                    b.Property<string>("TraceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TraceId");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("Asynkron.OtelReceiver.Data.MetricEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string[]>("AttributeMap")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("EndTimestamp")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("Proto")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<decimal>("StartTimestamp")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Metrics");
                });

            modelBuilder.Entity("Asynkron.OtelReceiver.Data.SpanAttributeEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("Key", "Value");

                    b.ToTable("SpanAttributes");
                });

            modelBuilder.Entity("Asynkron.OtelReceiver.Data.SpanEntity", b =>
                {
                    b.Property<string>("SpanId")
                        .HasColumnType("text");

                    b.Property<string[]>("AttributeMap")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<long>("EndTimestamp")
                        .HasColumnType("bigint");

                    b.Property<string[]>("Events")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("OperationName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ParentSpanId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("Proto")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("StartTimestamp")
                        .HasColumnType("bigint");

                    b.Property<string>("TraceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SpanId");

                    b.HasIndex("EndTimestamp");

                    b.HasIndex("OperationName");

                    b.HasIndex("ServiceName");

                    b.HasIndex("SpanId");

                    b.HasIndex("StartTimestamp");

                    b.HasIndex("TraceId");

                    b.ToTable("Spans");
                });

            modelBuilder.Entity("Asynkron.OtelReceiver.Data.SpanNameEntity", b =>
                {
                    b.Property<string>("ServiceName")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("ServiceName", "Name");

                    b.ToTable("SpanNames");
                });

            modelBuilder.Entity("Asynkron.OtelReceiver.Data.LogAttributeEntity", b =>
                {
                    b.HasOne("Asynkron.OtelReceiver.Data.LogEntity", "Log")
                        .WithMany("Attributes")
                        .HasForeignKey("LogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Log");
                });

            modelBuilder.Entity("Asynkron.OtelReceiver.Data.LogEntity", b =>
                {
                    b.Navigation("Attributes");
                });
#pragma warning restore 612, 618
        }
    }
}
