// <auto-generated />
using Asynkron.OtelReceiver.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Asynkron.OtelReceiver.Migrations
{
    [DbContext(typeof(OtelReceiverContext))]
    [Migration("20251103172313_OptimizeSearchIndexes")]
    partial class OptimizeSearchIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("Asynkron.OtelReceiver.Data.LogAttributeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LogId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key");

                    b.HasIndex("LogId");

                    b.HasIndex("Value");

                    b.HasIndex("Key", "Value");

                    b.HasIndex("LogId", "Key", "Value");

                    b.ToTable("LogAttributes");
                });

            modelBuilder.Entity("Asynkron.OtelReceiver.Data.LogEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("ObservedTimestamp")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Proto")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("RawBody")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte>("SeverityNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SeverityText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SpanId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Timestamp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TraceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TraceId");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("Asynkron.OtelReceiver.Data.MetricEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AttributeMap")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ulong>("EndTimestamp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Proto")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<ulong>("StartTimestamp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Metrics");
                });

            modelBuilder.Entity("Asynkron.OtelReceiver.Data.SpanAttributeEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Key", "Value");

                    b.ToTable("SpanAttributes");
                });

            modelBuilder.Entity("Asynkron.OtelReceiver.Data.SpanAttributeValueEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SpanId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key");

                    b.HasIndex("SpanId");

                    b.HasIndex("Value");

                    b.HasIndex("Key", "Value");

                    b.HasIndex("SpanId", "Key", "Value");

                    b.ToTable("SpanAttributeValues");
                });

            modelBuilder.Entity("Asynkron.OtelReceiver.Data.SpanEntity", b =>
                {
                    b.Property<string>("SpanId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AttributeMap")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("EndTimestamp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Events")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OperationName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentSpanId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Proto")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("StartTimestamp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TraceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SpanId");

                    b.HasIndex("EndTimestamp");

                    b.HasIndex("OperationName");

                    b.HasIndex("ServiceName");

                    b.HasIndex("SpanId");

                    b.HasIndex("StartTimestamp");

                    b.HasIndex("TraceId");

                    b.HasIndex("ServiceName", "EndTimestamp");

                    b.HasIndex("ServiceName", "StartTimestamp");

                    b.HasIndex("TraceId", "StartTimestamp");

                    b.ToTable("Spans");
                });

            modelBuilder.Entity("Asynkron.OtelReceiver.Data.SpanNameEntity", b =>
                {
                    b.Property<string>("ServiceName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("ServiceName", "Name");

                    b.ToTable("SpanNames");
                });

            modelBuilder.Entity("Asynkron.OtelReceiver.Data.LogAttributeEntity", b =>
                {
                    b.HasOne("Asynkron.OtelReceiver.Data.LogEntity", "Log")
                        .WithMany("Attributes")
                        .HasForeignKey("LogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Log");
                });

            modelBuilder.Entity("Asynkron.OtelReceiver.Data.SpanAttributeValueEntity", b =>
                {
                    b.HasOne("Asynkron.OtelReceiver.Data.SpanEntity", "Span")
                        .WithMany()
                        .HasForeignKey("SpanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Span");
                });

            modelBuilder.Entity("Asynkron.OtelReceiver.Data.LogEntity", b =>
                {
                    b.Navigation("Attributes");
                });
#pragma warning restore 612, 618
        }
    }
}
